klas1 = 'oga4b' # Laurens
klas2 = 'oga4b' # Madelief
klas3 = 'oga4' # Allebei


Lokalen = [
    "beuk3_gym",
    "tm047_gym",
    "tm046_gym",
    "tm116_binask",
    "tm128_tmc",
    "tm145_o&o",
    "tm146_o&o",
    "cb012_gym",
    "tm116_binask\, tm115_binask",
    "tm034\, tm035",
    "tm208\, tm214\, tm137\, tm215",
    "tm208\, tm137\, tm214\, tm215",
    "cb110_dvpr",
    "veld1",
    "veld2",
    "tm018_muziek",
    "tm222\, tm223\, tm224",
    "ut006",
]

Lessen = {
    f'{klas3}.bl1': 'Begeleidingslessen',
    f'{klas3}.bl3': 'Begeleidingslessen',
    f'{klas3}.biol1': 'Biologie',
    f'{klas3}.ckvnieuw1': 'Culturele en Kunstzinnige Vorming',
    f'{klas3}.ckvnieuw2': 'Culturele en Kunstzinnige Vorming',
    f'{klas3}.dutl1': 'Duits',
    f'{klas3}.econ1': 'Economie',
    f'{klas1}entl': 'Engels',
    f'{klas3}.fatl1': 'Frans',
    f'{klas1}lo': 'Lichamelijke Opvoeding',
    f'oga4.kua1\, oga5.kua1': 'Kunst Algemeen',
    f'oga5.kua1\, oga4.kua1': 'Kunst Algemeen',
    f'oga6.kumu1\, oga4.kumu1\, oga5.kumu1\, oh5.kumu1\, oh4.kumu1': 'Kunst (Muziek)',
    f'oh4.kumu1\, oga5.kumu1\, oga6.kumu1\, oh5.kumu1\, oga4.kumu1': 'Kunst (Muziek)',
    f'oh4.kumu1\, oga5.kumu1\, oga4.kumu1\, oga6.kumu1\, oh5.kumu1': 'Kunst (Muziek)',
    f'oh5.kumu1\, oga6.kumu1\, oga4.kumu1\, oga5.kumu1\, oh4.kumu1': 'Kunst (Muziek)',
    f'oga6.kumu1\, oga5.kumu1\, oga4.kumu1\, oh5.kumu1\, oh4.kumu1': 'Kunst (Muziek)',
    f'oga4.kumu1\, oh4.kumu1\, oh5.kumu1\, oga5.kumu1\, oga6.kumu1': 'Kunst (Muziek)',
    f'oh5.kumu1\, oga5.kumu1\, oga6.kumu1\, oh4.kumu1\, oga4.kumu1': 'Kunst (Muziek)',
    f'{klas1}maat': 'Maatschappijleer',
    f'{klas3}.mentor1': 'Mentor',
    f'{klas3}.mentor3': 'Mentor',
    f'{klas3}.nat1': 'Natuurkunde',
    f'{klas1}netl': 'Nederlands',
    f'oga4.o&o1\, oga6.o&o1\, oga5.o&o1': 'Onderzoeken en Ontwerpen',
    f'oga4.o&o1\, oga5.o&o1\, oga6.o&o1': 'Onderzoeken en Ontwerpen',
    f'oga5.o&o1\, oga4.o&o1\, oga6.o&o1': 'Onderzoeken en Ontwerpen',
    f'oga6.o&o1\, oga5.o&o1\, oga4.o&o1': 'Onderzoeken en Ontwerpen',
    f'oga6.o&o1\, oga4.o&o1\, oga5.o&o1': 'Onderzoeken en Ontwerpen',
    f'{klas3}.schk1': 'Scheikunde',
    f'{klas3}.wisa1': 'Wiskunde',
    f'{klas3}.wisb2': 'Wiskunde',
    f'Les - en' : 'Engels',
    f'Les - wi' : 'Wiskunde',
    f'Les - fa' : 'Frans',
    f'Les - ne' : 'Nederlands',
    f'Les - ec' : 'Economie',
    f'Les - sk' : 'Scheikunde',
    f'Les - na' : 'Natuurkunde',
    f'Les - gs' : 'Geschiedenis',
    f'Les - du' : 'Duits',
    f'Les - ak' : 'Aardrijkskunde',
    f'Les - mentor' : 'Mentor',
}