klas1 = 'oga3c' # Laurens
klas2 = 'oga3b' # Madelief


Lokalen = [
    "SUMMARY:beuk3_gym - ",
    "SUMMARY:tm047_gym - ",
    "SUMMARY:tm046_gym - ",
    "SUMMARY:tm116_binask - ",
    "SUMMARY:tm128_tmc - ",
    "SUMMARY:tm145_o&o - ",
    "SUMMARY:tm146_o&o - ",
    "SUMMARY:cb012_gym - ",
    "SUMMARY:tm116_binask\, tm115_binask - ",
    "SUMMARY:tm034\, tm035 - ",
    "SUMMARY:tm208\, tm214\, tm137\, tm215 - ",
    "SUMMARY:tm208\, tm137\, tm214\, tm215 - ",
    "SUMMARY: - ",
    "SUMMARY:cb110_dvpr - ",
    "SUMMARY:veld1 - ",
    "SUMMARY:veld2 - ",
]

Lessen = {
    f'{klas1}ak': 'Aardrijkskunde',
    f'{klas1}bl': 'Begeleidingslessen',
    f'{klas1}du': 'Duits',
    f'{klas1}ec': 'Economie',
    f'{klas1}en': 'Engels',
    f'{klas1}fa': 'Frans',
    f'{klas1}gs': 'Geschiedenis',
    f'{klas1}lo': 'Lichamelijke Opvoeding',
    f'{klas1}mentor': 'Mentor',
    f'{klas1}na': 'Natuurkunde',
    f'{klas1}ne': 'Nederlands',
    f'{klas1}o&o': 'Onderzoeken en Ontwerpen',
    f'{klas1}sk': 'Scheikunde',
    f'{klas1}wi': 'Wiskunde',
    f'{klas2}ak': 'Aardrijkskunde',
    f'{klas2}bl': 'Begeleidingslessen',
    f'{klas2}du': 'Duits',
    f'{klas2}ec': 'Economie',
    f'{klas2}en': 'Engels',
    f'{klas2}fa': 'Frans',
    f'{klas2}gs': 'Geschiedenis',
    f'{klas2}lo': 'Lichamelijke Opvoeding',
    f'{klas2}mentor': 'Mentor',
    f'{klas2}na': 'Natuurkunde',
    f'{klas2}ne': 'Nederlands',
    f'{klas2}o&o': 'Onderzoeken en Ontwerpen',
    f'{klas2}sk': 'Scheikunde',
    f'{klas2}wi': 'Wiskunde',
    f'oga3.tmc1, oh3.tmc1': 'TMC',
    f'oga3.tmc1\, oh3.tmc1' : 'TMC',
    f'oh3.tmc1, oga3.tmc1': 'TMC',
    f'oh3.tmc1\, oga3.tmc1' : 'TMC',
    f'oga3.bl2' : 'Begeleidingslessen',
    f'oga3.mentor2' : 'Mentor',
    f'Les - en' : 'Engels',
    f'Les - wi' : 'Wiskunde',
    f'Les - fa' : 'Frans',
    f'Les - ne' : 'Nederlands',
    f'Les - ec' : 'Economie',
    f'Les - sk' : 'Scheikunde',
    f'Les - na' : 'Natuurkunde',
    f'Les - gs' : 'Geschiedenis',
    f'Les - du' : 'Duits',
    f'Les - ak' : 'Aardrijkskunde',
    f'Les - mentor' : 'Mentor',
}